### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by ghost** [vingojw/vue-vueRoute-webpack#1]
Unhandled rejection Error: ENOENT: no such file or directory, open 'build/assets.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Compiler.<anonymous> (/study/webpack-study/examples/vue-vueRouter-webpack/webpack.config.js:59:19)
    at Compiler.applyPlugins (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:58:19)
    at /study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/webpack/lib/Compiler.js:267:14)
    at /study/webpack-study/examples/vue-vueRouter-webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/study/webpack-study/examples/vue-vueRouter-webpack/node_modules/async/lib/async.js:209:22)

**Comment by vingojw** [comment]
已修复。之前是想在webpack运行结束之后，拿到文件的hash值。
https://github.com/vingojw/vue-vueRouter-webpack/blob/master/webpack.config.js#L59
